name: ac-lab

services:
  db:
    image: postgres:18-alpine
    networks:
      - ac-lab-network
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
  app:
    build:
      context: .
      dockerfile: Dockerfile
    init: false
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - ac-lab-network

  loki:
    image: grafana/loki:3.7.2
    ports:
      - "3100:3100"
    networks:
      - ac-lab-network

  grafana:
    image: grafana/grafana:9.1.7
    ports:
      - "10000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - loki
    networks:
      - ac-lab-network

volumes:
  postgres-data:

networks:
  ac-lab-network:
