apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: aclab
  labels:
    app: app
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: app
          image: warek01/aclab1:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: aclab-secrets
          resources:
            requests:
              memory: 256Mi
              cpu: 250m
            limits:
              memory: 1024Mi
              cpu: 1000m
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
              host: localhost
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
              host: localhost
            initialDelaySeconds: 20
            periodSeconds: 10

---

apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: aclab
spec:
  selector:
    app: app
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30002
  type: NodePort