apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: aclab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:9.1.7
          ports:
            - containerPort: 3000
          env:
            - name: GF_SECURITY_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: password
            - name: GF_SECURITY_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: grafana-secret
                  key: username
            - name: GF_SERVER_ROOT_URL
              valueFrom:
                configMapKeyRef:
                  name: grafana-config-map
                  key: grafanaRootUrl
            - name: GF_SERVER_SERVE_FROM_SUB_PATH
              valueFrom:
                configMapKeyRef:
                  name: grafana-config-map
                  key: grafanaServeFromSubpath

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: aclab
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
  type: ClusterIP
