name: CI Checks
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  ci-checks:
    name: Build & Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 25
          cache: gradle
          distribution: temurin
      - name: Unit Test
        run: |
          ./gradlew build
